Capstone Exercise - AfriCities Summit 2022
WalterOkumu/microverse-capstone-1 pull request #1
Opened 2022-08-02 21:12 UTC by WalterOkumu

- Set up linters
- Replicated design from guidelines
- Customized page as per AfriCities Summit site
- Added images from past events

2022-08-02 21:59 UTC, VICTOR-CHUKWU requested changes
Hi @WalterOkumu , 
## STATUS: CHANGES REQUIRED :recycle: 
Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-08-02 21:59 UTC, VICTOR-CHUKWU commented on index.html
>          <h1>The 9th AfriCities Summit 2022</h1>
- [ ] as your are allowed to have a different content from the given design, the project require that you stick to color and font size, Kindly fix the color and font size of you `h1` tag.
  your design :point_down: 
![Screenshot from 2022-08-02 22-37-43](https://user-images.githubusercontent.com/66097371/182478502-939013e3-f9df-47b7-a08c-cda8e268f475.png)
project design :point_down: 
![Screenshot from 2022-08-02 22-42-10](https://user-images.githubusercontent.com/66097371/182478660-8005adfd-b988-4f83-ac09-0ceab24b4705.png)

2022-08-02 21:59 UTC, VICTOR-CHUKWU commented on styles/sass/main.scss
> +              width: 35%;
- [ ] Kindly align your card title by making the width bigger than 35%, it currently looks not too good
![Screenshot from 2022-08-02 22-44-21](https://user-images.githubusercontent.com/66097371/182479375-e384f691-04fc-42c5-9aae-012b161afa7f.png)

2022-08-02 21:59 UTC, VICTOR-CHUKWU commented on about.html
>        <div class="desktop-navbar">
- [ ] Your about page destop view should have a dark background footer, kindly fix this
  
![Screenshot from 2022-08-02 22-51-15](https://user-images.githubusercontent.com/66097371/182480144-f3c8ae8f-52f6-4dc9-bc6e-1959cf5943f7.png)

2022-08-02 21:59 UTC, VICTOR-CHUKWU commented on README.md
> +## Live Demo (if available)
- [ ] Images in your live page is broken, kindly fix this
![Screenshot from 2022-08-02 22-55-19](https://user-images.githubusercontent.com/66097371/182480397-296af49b-4dd6-4731-aee3-4ae32de20039.png)

2022-08-02 21:59 UTC, VICTOR-CHUKWU commented on README.md
> +## Acknowledgments
- [ ] Your  README should contain an "Acknowledgements" section or similar that gives appropriate credit to Cindy Shin] the author of the original design.

2022-08-03 08:30 UTC, mikethreels approved these changes
Hi Okumu, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-03 08:30 UTC, merged